WARNING: Error in initializing MVAPICH2 ptmalloc library.Continuing without InfiniBand registration cache support.
Traceback (most recent call last):
  File "shortage_duration_curves_ratio.py", line 188, in <module>
    histData_shortage = np.loadtxt('../../../LHsamples_original_1000_AnnQonly/Infofiles/' +  all_IDs[i] + '/' + all_IDs[i] + '_info_hist.txt')[:,2]
  File "/opt/python/lib/python3.6/site-packages/numpy-1.17.0-py3.6-linux-x86_64.egg/numpy/lib/npyio.py", line 968, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/python/lib/python3.6/site-packages/numpy-1.17.0-py3.6-linux-x86_64.egg/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/python/lib/python3.6/site-packages/numpy-1.17.0-py3.6-linux-x86_64.egg/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: ../../../LHsamples_original_1000_AnnQonly/Infofiles/3804617/3804617_info_hist.txt not found.
[comet-23-02.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 4, pid: 20089) exited with status 1
